{
 "title": "Sustainability (Workload Benchmarking)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg_over_time(powerstat[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Phase Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT \r\n    TIMESTAMPDIFF(MINUTE, $__timeFrom(), $__timeTo()) AS DurationInMinutes\r\n"
    }
   ]
  },
  {
   "title": "Machine Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(powerstat[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Energy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(powerstat[$__interval])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine CO2 ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((((avg_over_time(powerstat[$__interval])/16.667)*0.82)/60)*5)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}