---
- name: PostgreSQL installation on cluster nodes
  hosts: localhost
  tasks:
    - name: update nodes
      become: true
      apt:
        update_cache: yes

    - name: Install postgresql postgresql-contrib
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - postgresql-14
        - postgresql-contrib-14

    - name: Start service
      become: true
      service:
        name: postgresql
        state: started
